name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Debug info
      run: |
        echo "GitHub ref: ${{ github.ref }}"
        echo "GitHub ref type: ${{ github.ref_type }}"
        echo "Tag name: ${{ github.ref_name }}"
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        cp Gemfile.production Gemfile
        # Temporarily enable coveralls for CI
        sed -i 's/# spec.add_development_dependency "coveralls"/spec.add_development_dependency "coveralls"/' vergissberlin.gemspec
        bundle install
    
    - name: Build gem
      run: gem build vergissberlin.gemspec
    
    - name: Publish to RubyGems
      run: gem push vergissberlin-*.gem
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
